name: Dependency Update
on:
  schedule:
    - cron: "0 0 * * 1" # Every monday at midnight
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Update Maven dependencies
        working-directory: ./apps/backend
        run: |
          ./mvnw versions:update-properties
          ./mvnw versions:use-latest-versions

      # Todo: Add support for frontend (when available)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "Automated dependency update"
          body: |
            This PR updates all dependencies to their latest versions.
            Please review the changes and test thoroughly before merging.
          branch: dependency-update
          delete-branch: true
